apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: models.config.onosproject.org
spec:
  group: config.onosproject.org
  scope: Namespaced
  names:
    kind: Model
    listKind: ModelList
    plural: models
    singular: model
    shortNames:
      - db
  versions:
    - name: v1beta1
      served: true
      storage: true
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          required:
            - spec
          properties:
            spec:
              type: object
              required:
                - type
                - version
                - yangModels
              properties:
                type:
                  type: string
                version:
                  type: string
                yangModels:
                  type: array
                  items:
                    type: object
                    required:
                      - name
                      - version
                      - data
                    properties:
                      name:
                        type: string
                      organization:
                        type: string
                      version:
                        type: string
                      data:
                        type: string
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: services.topo.onosproject.org
spec:
  group: topo.onosproject.org
  scope: Namespaced
  names:
    kind: Service
    listKind: ServiceList
    plural: services
    singular: service
  versions:
    - name: v1beta1
      served: true
      storage: true
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                selector:
                  type: object
                model:
                  type: object
                  required:
                    - name
                  properties:
                    name:
                      type: string
                    namespace:
                      type: string
                config:
                  type: object
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: entities.topo.onosproject.org
spec:
  group: topo.onosproject.org
  scope: Namespaced
  names:
    kind: Entity
    listKind: EntityList
    plural: entities
    singular: entity
  versions:
    - name: v1beta1
      served: true
      storage: true
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
                - kind
              properties:
                kind:
                  type: object
                  required:
                    - name
                  properties:
                    name:
                      type: string
                    namespace:
                      type: string
                attributes:
                  type: object
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: relations.topo.onosproject.org
spec:
  group: topo.onosproject.org
  scope: Namespaced
  names:
    kind: Relation
    listKind: RelationList
    plural: relations
    singular: relation
  versions:
    - name: v1beta1
      served: true
      storage: true
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
                - kind
                - source
                - target
              properties:
                kind:
                  type: object
                  required:
                    - name
                  properties:
                    name:
                      type: string
                    namespace:
                      type: string
                source:
                  type: object
                  required:
                    - name
                  properties:
                    name:
                      type: string
                    namespace:
                      type: string
                target:
                  type: object
                  required:
                    - name
                  properties:
                    name:
                      type: string
                    namespace:
                      type: string
                attributes:
                  type: object
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: kinds.topo.onosproject.org
spec:
  group: topo.onosproject.org
  scope: Namespaced
  names:
    kind: Kind
    listKind: KindList
    plural: kinds
    singular: kind
  versions:
    - name: v1beta1
      served: true
      storage: true
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                attributes:
                  type: object