apiVersion: core.onosproject.org/v1beta1
kind: Application
metadata:
  name: my-xapp
spec:
  replicas: 3
  image: onosproject/my-xapp:latest
  language:
    name: go
    version: 1.14
  config:
    model:
      name: ric
      compiler:
        image: onosproject/config-model-compiler:latest
  logging:
    loggers:
      root:
        level: debug