# A sample configuration Model for configuring a RIC component.
apiVersion: config.onosproject.org/v1beta1
kind: Model
metadata:
  name: ric
spec:
  version: 1.0.0
  modules:
    - name: test
      version: 2020-11-18
      data: |
        module test {
          namespace "http://opennetworking.org/oran/test";
          prefix t1;

          organization
            "Open Networking Foundation.";
          contact
            "Adib Rastegarnia";
          description
            "To generate JSON from this use command
             pyang -f jtoxx test1.yang | python3 -m json.tool > test1.json
             Copied from YangUIComponents project";

          revision 2020-11-18 {
            description
              "Extended with new attributes on leaf2d, list2b";
            reference
              "RFC 6087";
          }

          container cont1a {
            description
              "The top level container";
            leaf leaf1a {
              type string {
                length "1..80";
              }
              description
                "display name to use in GUI or CLI";
            }
            leaf leaf2a {
              type string {
                length "1..255";
              }
              description
                "user plane name";
            }
          }
        }
---
# This Deployment defines Deployment annotated for config model injection
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-xapp
  annotations:
    config.onosproject.org/inject: model
    config.onosproject.org/model: ric
    config.onosproject.org/compiler-language: go
    config.onosproject.org/compiler-version: latest
spec:
  replicas: 1
  selector:
    matchLabels:
      name: my-xapp
  template:
    metadata:
      labels:
        name: my-xapp
    spec:
      containers:
        - name: my-xapp
          image: onosproject/my-xapp:latest